[package]
name = "cloud-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
dialoguer = "0.12.0"
clap = { version = "4.6.7", features = ["derive"] }
regex = "1.13.1"
reqwest = "0.13.5"
tokio = { version = "1", features = ["full"]}
cloud-core = { path = "../cloud-core" }
cloud-api = { path = "../cloud-api" }
