[package]
name = "cloud-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum = { version = "0.8", features = ["ws"]}
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
cloud-core = { path = "../cloud-core" }

[dev-dependencies]
tempfile = "3.27"
tower = { version = "0.5", features = ["util"] }
